export const MOVIES_ADD_FROM_SERVER = 'MOVIES_ADD_FROM_SERVER';
export const START_REQUEST_MOVIES = 'START_REQUEST_MOVIES';
export const FINISH_REQUEST_MOVIES = 'FINISH_REQUEST_MOVIES';
export const MOVIES_FETCH_REQUESTED = 'MOVIES_FETCH_REQUESTED';
export const CHANGE_FILTER_TEXT = 'CHANGE_FILTER_TEXT';
